### ISSUE TITLE
[QGIS 3.0.1] Metadata Error QGIS Version

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/qgis-wfsOutputExtension#1]
Hi guys,
for QGIS 3.0.1 this is plugin is broken. "Is incompatible with this version of QGIS Plugin designed for QGIS 2.8 - 2.99"

I change the qgis minimum version in metadata.txt but then give an error of import PyQt4 module probable need code migration.

Regards
João

**Comment by pcav** [comment]
An important issue, now that QGIS 2.18 is end of life

**Comment by rldhont** [comment]
@jonnyforestGIS the plugin has been refactorized for QGIS 3

**Comment by pcav** [comment]
Not yet published?
Thanks.

**Comment by rldhont** [comment]
first one https://github.com/3liz/qgis-wfsOutputExtension/releases/tag/v1.1.0

second and last one https://github.com/3liz/qgis-wfsOutputExtension/releases/tag/v1.2.0
