### ISSUE TITLE
[CDATA[<text]] in exported xlsx tables

### ISSUE THREAD

**Issue by tethysgeco** [3liz/qgis-wfsOutputExtension#17]
When there are special characters in text fields (e.g. < or &) in exported excel tables we find <![CDATA[<text]] (no error message is returned opening xlsx file).

**Comment by Gustry** [comment]
It seems the issue is upstream in QGIS : https://github.com/qgis/QGIS/blob/master/src/server/services/wfs/qgswfsgetfeature.cpp#L1550
To fix this, either it would need a fix in QGIS Server, or search/replace (refactor field algo) after getting the GML.

**Comment by Gustry** [comment]
This should be fixed in QGIS Server 3.24.1 and 3.22.6.

Thanks to @pcav for funding this bugfix.
