### ISSUE TITLE
Critical error when writing to QTemporaryFile

### ISSUE THREAD

**Issue by MattiasSp** [3liz/qgis-wfsOutputExtension#18]
I'm using QGIS Server 3.14.16 with wfsOutputExtension 1.4.1 and I'm getting the following error in the QGIS log:

`CRITICAL wfsOutputExtension[2656]: Creation of data source failed (OGR error: It seems a file system object called '[my QGIS temp folder]/request-WFS-qzMlsS.csv' already exists.)`

It seems that writing works when I edited `wfs_filter.py` to not open the QTemporaryFile (`temporary.open()` which I think is what creates the file).

The error occurs with all output formats. Any idea what might prevent wfsOutputExtension from overwriting the file?

**Comment by rldhont** [comment]
Please update to 1.5.0 and get feedback.

**Comment by MattiasSp** [comment]
I updated to 1.5.0 (sorry, missed that there was a new release). Unfortunately the error persists, although the paths changed:

`CRITICAL wfsOutputExtension[7360]: Creation of data source failed (OGR error: It seems a file system object called '[my QGIS temp folder]/QGIS_WfsOutputExtension/to-csv-CzvWgr.csv' already exists.)`

**Comment by MattiasSp** [comment]
Perhaps the QTemporaryFile needs to be removed instead of closed?

This seems to suggest so:
https://forum.qt.io/topic/66643/qtemporaryfile-close-method

Changing the call [temporary.close()](https://github.com/3liz/qgis-wfsOutputExtension/blob/cec08bf2edbf94d28ac88f604ce04477a7584ad9/wfsOutputExtension/wfs_filter.py#L241) to `temporary.remove()` also seems to fix my issue.
