### ISSUE TITLE
wfsoutputExtension windows server compatibility

### ISSUE THREAD

**Issue by pritamashutosh** [3liz/qgis-wfsOutputExtension#19]
is this extension is compatible with windows server?

if so how to enable this?

Regards

**Comment by Gustry** [comment]
No one from us is using Windows.
Your question is more related to how to install a QGIS Server plugin on Windows.

Maybe a have look there https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows
or in the official QGIS Documentation related to QGIS Server : https://docs.qgis.org/3.16/en/docs/server_manual/

I'm closing this issue as it's not specific to WfsOutputExtension.
You can still share feedback.
