### ISSUE TITLE
Installation returns no attribute 'classFactory' error

### ISSUE THREAD

**Issue by dobignies** [3liz/qgis-wfsOutputExtension#2]
Hello, masters
I tried to install from plugin manager (Qgis 3.6.1), but there is something wrong. The phyton error log returns:

  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
             plugins[packageName] = package.classFactory(iface)
             AttributeError: module 'qgis-wfsOutputExtension-master' has no attribute 'classFactory'

any idea?

**Comment by dobignies** [comment]
Hi,
I forgot some details: I use LWC master and Windows 10.
I'd tried qgis2to3 scripts in version 1.0.1 solving the classfactory and Qdialog issues, but I can't handle the  resources and ui files.
GetCapabilities returns only GeoJSON and GML. Nevertheless, the export function in Lizmap shows all formats, but it returns broken zip files (0 bytes).
No changes installing plugin's folder in \apps\qgis\python\plugins (set in php73.conf) or \QGIS3\profiles\default\python\plugins.
I appreciate any help.
best regards

**Comment by rldhont** [comment]
@dobignies the plugin has just been refactorized for QGIS 3. Test new version.

**Comment by rldhont** [comment]
needed for window qgis server plugins

**Comment by rldhont** [comment]
@Gustry does this commit https://github.com/3liz/qgis-wfsOutputExtension/commit/f0664c19953f460f99dc78a441aeeef46d3dc80f fix this issue ?

**Comment by Gustry** [comment]
Yes, it should. The plugin is useless on QGIS Desktop.
