### ISSUE TITLE
Remove temporary files

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-wfsOutputExtension#21]
## Description

There is nothing to remove temporary files.

* Temporary GML, it looks easy, as soon as we have the `QgsFileVectorWritter` in the new format, we can remove the GML file.
* Temporary target extension, need to check for that one

**Comment by Gustry** [comment]
Fixed in 80012147c49c69b5e36b86b2ef5dd58f7e90870e

After this fix @lhirlimann, the folder must **stay** empty everytime, at the end of the HTTP request.  But do not remove it.

**Comment by lhirlimann** [comment]
Maybe I d' like a release after all.
