### ISSUE TITLE
Is a stable relase planned?

### ISSUE THREAD

**Issue by Guts** [3liz/qgis-wfsOutputExtension#25]
Hi there,

Nice plugin, thanks!

Is there a reason why the plugin is still flagged as experimental after 5 years? Do you plan to release it as stable?
It's for a friend :wink: 

![image](https://user-images.githubusercontent.com/1596222/111662778-852b6500-8810-11eb-9f6d-a090d9158e14.png)

**Comment by Gustry** [comment]
It's not only planned, it has already been done. Same thought as you 21 days ago : https://github.com/3liz/qgis-wfsOutputExtension/commit/f27d89ea0f05835908f08d4d1619ae4472707671 ;-)

I haven't noticed this for a long time.

Thanks for reporting it !
