### ISSUE TITLE
Does not work on newer versions of QGIS Server

### ISSUE THREAD

**Issue by mibalas** [3liz/qgis-wfsOutputExtension#28]
Hi, Does this plugin work on the latest versions of QGIS Server?

I'm trying to use this plugin on QGIS Server versions 3.16 and 3.18 with LWC but without success. 
I tested the HelloServer plugin and it worked.

My WFS GetCapabilities does not show other options for export, only geojson/gml.

I already cleaned the temp/lizmap

I don't know how to install older versions of QGIS Server.

My specs:
Debian 10
LWC 3.3.12
QGIS SERVER 3.16

Thank you

**Comment by Gustry** [comment]
AFAIK, we have no known issues with 3.16. We have people using it, and tests are passing with 3.16, 3.10 and 3.4 :  
https://github.com/3liz/qgis-wfsOutputExtension/actions/runs/812032296

You should check your QGIS Server logs and check any error/warning message.

> LWC 3.3.12
QGIS SERVER 3.16

This is probably not a so good idea. LWC 3.3 is not fully compatible with QGIS Server 3.16. In Lizmap plugin, first panel, you should have a warning with your QGIS Desktop 3.16 when you select LWC 3.3.

![Screenshot from 2021-07-21 09-26-28](https://user-images.githubusercontent.com/1609292/126448733-23aaafe2-c092-4313-8ee9-f1336dd357c8.png)

**Comment by mibalas** [comment]
Hi, I'm new to QGIS Server I don't know where the logs are.

I think it wouldn't have to do with the LWC version because my QGIS Server WFS link doesn't show the new options:

http://localhost/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities
![image](https://user-images.githubusercontent.com/15907968/126541160-9c21237a-0cb7-4d8b-8153-713b3dce6ab3.png)

I installed LWC 3.4 but nothing has changed

**Comment by Gustry** [comment]
> Hi, I'm new to QGIS Server I don't know where the logs are.

You need to read the QGIS Server documentation :
https://docs.qgis.org/3.16/en/docs/server_manual/config.html#logging

> I think it wouldn't have to do with the LWC version because my QGIS Server WFS link doesn't show the new options:

Sorry I don't understand. We can see geojson in your screenshot. Do you have all other formats in the output ? It seems QGIS Server plugin is working.
Try to clean the cache again in LWC ?

**Comment by mibalas** [comment]
I would like to export to other formats like CVS/XLS as in the examples:
![image](https://user-images.githubusercontent.com/15907968/126780882-7e3ecaf4-1802-4381-8b80-a25c042a1b40.png)

lizmap:
![image](https://user-images.githubusercontent.com/15907968/126781085-63a937b9-90c4-4328-b309-bd508af6a5ab.png)

But only appear the options GML/GEOJSON

I tried to configure the QGIS log, setting the variables in apache conf but nothing appears. I don't know what happens with Debian.

**Comment by Gustry** [comment]
Hi, I hope you found the source of the problem.
Check file permissions, folder owner etc.
QGIS Server must be able to execute the code in the folder.
[QGIS-plugin-manager](https://github.com/3liz/qgis-plugin-manager) might help in detecting the user permission.

I'm closing the issue, the plugin works well with 3.16.
