### ISSUE TITLE
Field format altered text to numeric when exporting in csv/xlsx

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/qgis-wfsOutputExtension#31]
## Description

When downloading a layer in csv or xlsx, type of field is changed. From text to numeric. 
Very annoying on insee code cause dep Aisne : initially 02*** became 2***

Please, look at this example : https://geocatalogue.hautsdefrance.fr/geonetwork/srv/fre/catalog.search;jsessionid=54BF46D02CD9744DD1523E68AB154BD1?node=srv#/metadata/4b5f8e1b-de37-47cd-9203-37a59f318b09

## Context

* QGIS Server FULL version (with 3 numbers) : QGIS-Server-3.16.14
* OS on the server : Linux Debian 10 Buster

**Comment by Doctor-Who** [comment]
Up ?

**Comment by u-cav** [comment]
We are also seeing this issue with Lizmap 3.5.0. The same layer is exported correctly from QGIS Desktop (with leading zeroes, if the field type is text).

**Comment by rldhont** [comment]
@pcav it is an issue due to the way GDAL is sniffing field type.

**Comment by Doctor-Who** [comment]
@rldhont Could it be fix ? Which side ? Do we suppose to open a issue on GDAL project ?

**Comment by rldhont** [comment]
@Doctor-Who it is not a GDAL issue. We have deactivated Schema request to avoid GDAL from wfsOutputExtension in QGIS Server requesting QGIS Server (something like QGIS Server requesting QGIS server). I don't know if .gfs file can help here. https://gdal.org/drivers/vector/gml.html

**Comment by rldhont** [comment]
A way to fix it :
1. Get the XSD file with a DescribeFeatureType request
2. Open the GML file with the XSD file

**Comment by u-cav** [comment]
@Gustry @rldhont Thank you very much for the fix, it works perfectly.

**Comment by Doctor-Who** [comment]
@u-cav Fix funded by region of Hauts-de-France // https://www.hautsdefrance.fr/

**Comment by u-cav** [comment]
@Doctor-Who Great to know, thank you and thanks to la Région Hauts-de-France!

**Comment by Gustry** [comment]
Thanks for the reminder @Doctor-Who !
Thanks !

https://twitter.com/etrimaille/status/1507270134997598213
