### ISSUE TITLE
Temporary space not left after not enought space error

### ISSUE THREAD

**Issue by Niarolf** [3liz/qgis-wfsOutputExtension#37]
## Description
When we have not enought space in the apache temp filesystem, the temporary files are not deleted.

## Context
Qgis server is using with apache2 and fcgi.
The plugin variable debug is with the false value
When we call the plugin for a large file, send with a SHP outputFormat for example, the plugin create a gml file, then he converts this one in shp and finally in a zip file.
All theses files are deleted when no error and the final file is send, but when an error is occuring, the plugin stop, send a partial file and don't delete the temporary files.
We must delete manually.

* QGIS Server FULL version (with 3 numbers) :
Qgis Server 3.16.4

* OS on the server :
Debian 10.8

**Comment by Gustry** [comment]
Do you have the Python error which occurred ?

**Comment by Niarolf** [comment]
@Gustry 
Voici un extrait de l'erreur que j'ai dans le log qui semble être lié à OGR :
 11:21:04 WARNING OGR[58278]: Feature creation error (OGR error: Error in psSHP->sHooks.FWrite() while writing object of 21992 bytes to .shp file: Aucun espace disponible sur le périphérique)
11:21:04 WARNING OGR[58278]: Feature creation error (OGR error: Error in psSHP->sHooks.FWrite() while writing object of 16200 bytes to .shp file: Aucun espace disponible sur le périphérique)
11:21:04 CRITICAL WfsOutputExtension[58278]: Feature write errors:
Feature creation error (OGR error: Error in psSHP->sHooks.FWrite() while writing object of 63592 bytes to .shp file: Aucun espace disponible sur le périphérique)
Feature creation error (OGR error: Error in psSHP->sHooks.FWrite() while writing object of 8520 bytes to .shp file: Aucun espace disponible sur le périphérique)
Feature creation error (OGR error: Error in psSHP->sHooks.FWrite() while writing object of 68408 bytes to .shp file: Aucun espace disponible sur le périphérique)

Le fichier renvoyé au client est vide :
![image](https://user-images.githubusercontent.com/25381960/157642144-98c941b3-bdb3-473b-8ae6-bb58b6d42ba4.png)

**Comment by Gustry** [comment]
Please try the next version, files should always be removed in case of an exception.
