### ISSUE TITLE
install on nginx

### ISSUE THREAD

**Issue by infoble** [3liz/qgis-wfsOutputExtension#6]
Hi, I use qgis server 3.10 via spawn-fcgi and multiwatch, LWC 3.3 on a congig debian buster/nginx. I'm trying to install the plugin:
- unzipped plugin in the folder /opt/qgis-server/plugins
- "fastcgi_param QGIS_PLUGINPATH /opt/qgis-server/plugins;" add in the virtual host conf (in location /qgisserver {})
- qgis server and nginx restarted
Nothing changes in the getcapabilities, do I forget something ?
Thanks

**Comment by rldhont** [comment]
@Gustry @drillinP can you help ?

**Comment by Gustry** [comment]
@infoble Do you still have this issue?
Are you using SystemD for starting your spawn-fcgi? I personally don't use multiwatch.
Can you share QGIS Server logs ? (when it is starting, it will show which plugins are starting.)

Did you clean_vartmp in lizmap? The GetCapabilities is cached by Lizmap. Right @rldhont ?
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/clean_vartmp.sh

**Comment by Gustry** [comment]
Closing for lack of feedback
