### ISSUE TITLE
How can you install on a QGIS SERVER installation in windows with OSGeo4W?

### ISSUE THREAD

**Issue by Andrea996** [3liz/qgis-wfsOutputExtension#7]
How can you install on a QGIS SERVER installation in windows with OSGeo4W?

**Comment by rldhont** [comment]
Like any QGIS Server Plugin, you have to defined the varaible `QGIS_PLUGINPATH` in your fcgi QGIS Server config.

**Comment by Gustry** [comment]
@Andrea996 Do you still have the issue?

You should a look to your QGIS logs, it should tell you the default directory used for plugins. Then copy/paste the folder there and QGIS Server will detect it.

**Comment by Gustry** [comment]
Closing for lack of feedback, feel free to reopen.
